### ISSUE TITLE
App Works on iPhone but I get an Error / Warning...

### ISSUE THREAD

**Issue by inglesuniversal** [GetStream/react-native-audio-player#1]
Hi:

I was testing the code you kindly provided, tried it on an iPhone 6 and got a warning, even though after pressing on dismiss, the warning went away.... Is there some file I didn't  copy correctly?
Thanks, and I hope that we can also contribute for this open sourced project.

Attached image...

![image1](https://user-images.githubusercontent.com/15418158/30397583-f88f1bf2-9892-11e7-9896-110cd3693877.png)

**Comment by dwightgunning** [comment]
Hi! Thanks much for raising this issue.

There shouldn't be any need to copy any files, assuming you're running with the simulator. Though the error message would seem to indicate a bundling/packing issue.

Can you confirm the following versions:
 - Expo
 - iPhone simulator / build (or indeed the iOS version if you've packaged and deployed to a physical phone)
 -  commit SHA

I've just cloned the repo and launched the app without any issues, with the following:
 - Expo: Version 2.20.1 (2.20.1)
 - iPhone simulator: iOS 10.3 (14E8301)
 - commit SHA: dc07bb8 (current master)

**Comment by dwightgunning** [comment]
Hi @inglesuniversal - any chance you can provide those additional details about your dev/test environment so that we can replicate the error?

**Comment by dwightgunning** [comment]
Assigning @nparsons08 as he's lead on this project and best placed to assist.

**Comment by inglesuniversal** [comment]
How can I provide you with the details you are requesting... I have all the info except the commit SHA value... How do I get that in order to send it to you? Thanks

**Comment by dwightgunning** [comment]
If you're using git from the command line, it'll be in the top line next, e.g. "commit < SHA >" when you enter the following command at the root folder of the project: 

```bash
$ git status
```

For example:

```
commit dc07bb8e7acf93db10c724e3b5772bc1d54208b9
Author: Nick Parsons <nparsons08@gmail.com>
Date:   Wed Sep 6 15:20:24 2017 -0600

    Update README.md
```

**Comment by astrotars** [comment]
Closing this issue out due to inactivity. Please open a new issue if the problem persists. Thank you!
